### ISSUE TITLE
tiff/metadata: z/t dimensions and pixel size pulled when opening in imagej

### ISSUE THREAD

**Issue by adamkglaser** [acquire-project/acquire-driver-common#23]
I know there are different TIFF metadata specs, and have not dug into how they differ. But when dragging and opening a CPX output TIFF within ImageJ, the z/t dimensions are flipped (imagej thinks the tiff is many timepoints). And the voxel size in X/Y is interpreted as 1000000 um.

Is there a method to current set this within the CPX runtime? If not, should we start thinking about how to specify this?

**Comment by nclack** [comment]
This was fixed when we added pixel scale metadata support to the api.  Closing for now. Feel free to reopen if I got that wrong.
